- type: entity
  parent: BaseStructure
  id: PenumbraBaseWindowFrame
  name: window frame
  description: A big hole in the wall that used to sport a large window. Can be vaulted through.
  suffix: Penumbra
  abstract: true
  placement:
    mode: SnapgridCenter
    snap:
    - Wall
  components:
  - type: Transform
    anchored: true
  - type: Sprite
    drawdepth: Walls
  - type: PlacementReplacement
    key: walls
  - type: Damageable
    damageContainer: StructuralInorganic
    damageModifierSet: StructuralMetallic
  - type: StaticPrice
    price: 75
  - type: Physics
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,0.49"
        density: 1000
        mask:
        - MachineMask
        layer:
        - MidImpassable
  - type: Destructible
    thresholds:
      - trigger:
          !type:DamageTrigger
          damage: 600
        behaviors:
          - !type:DoActsBehavior
            acts: ["Destruction"]
          - !type:SpawnEntitiesBehavior
            spawn:
              SheetMetal1:
                min: 2
                max: 2
  - type: InteractionOutline
  - type: Clickable
  - type: Climbable
  - type: RequireProjectileTarget
  - type: Tag
    tags:
    - Structure
    - WindowFrame

- type: Tag
  id: WindowFrame
