- type: tile
  abstract: true
  id: PenumbraPlanetBase
  isSubfloor: true
  deconstructTools: [ ]
  footstepSounds:
    collection: FootstepGrass
  heatCapacity: 10000
  weather: true
  indestructible: true
