# Undersuit

- type: loadout
  id: PenumbraSecurityUniform
  equipment:
    jumpsuit: PenumbraClothingUniformSecurity

- type: loadout
  id: PenumbraSecurityUniformSkirt
  equipment:
    jumpsuit: PenumbraClothingUniformSecuritySkirt
